Fix AttributeError: module 'matplotlib' has no attribute 'axes' (#1955)
Co-authored-by: Nicki Skafte Detlefsen <skaftenicki@gmail.com>
(cherry picked from commit 7ed02ab29f8c84ecbe29a525aa36497eaed2db09)